export const GET_LATEST_TRANSACTIONS = 'GET_LATEST_TRANSACTIONS';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const SET_ADDRESS = 'SET_ADDRESS';

export const GET_PAIR = 'GET_PAIR';
export const PAIR_ERROR = 'PAIR_ERROR';